// Generated by CoffeeScript 1.12.4
(function() {
  var db, express, router;

  express = require('express');

  router = express.Router();

  db = require('./../libs/db');

  router.get('/', function(req, res, next) {

    /*res.send('服务器重启2'); */
    return db.users.insert({
      username: 'tom'
    }, function(err, user) {
      if (err) {
        return next(err);
      }
      console.log(user);
      res.json(user);
    });
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=index.js.map
