// Generated by CoffeeScript 1.12.4
(function() {
  angular.module('myApp').controller('LoginCtrl', [
    '$scope', '$location', '$http', 'tmsUtils', function($scope, $location, $http, tmsUtils) {
      $scope.userEntity = {
        username: '',
        password: '',
        rememberMe: false
      };
      $scope.doLogin = function() {
        $http.post(Tms.apiAddr + "/api/user/login", {
          username: $scope.userEntity.username,
          password: $scope.userEntity.password
        }).then(function(res) {
          var token;
          token = res.data.token;
          $http.defaults.headers.common['x-token'] = token;
          console.log("token=" + token);
          $location.path('/').replace();
        }, tmsUtils.processHttpError);
        return console.log($scope.userEntity);
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=loginCtrl.js.map
